import test from 'node:test';import assert from 'node:assert/strict';
import {initialState,startWorkout,newSet,finishWorkout,validateBackup,volume,bestFor,toDisplay,toKg,activityDays,localDay,csvExport,normalizeGroups} from './dist/core.mjs';
function fixture(){const s=initialState();s.settings.schedule=[];s.settings.scheduleHistory=[];s.settings.trackingSince='2026-09-01';const w=startWorkout(s);w.started='2026-09-21T10:00:00Z';w.entries=[{id:'entry',exerciseId:'bench-press',group:null,sets:[{...newSet(100,5),done:true},{...newSet(40,10,'warmup'),done:true},{...newSet(60,10,'drop'),done:true}]}];w.entries[0].sets.splice(1,1);s.workouts=[finishWorkout(w,'2026-09-21T11:00:00Z')];return s}
test('JSON round trip preserves complete state',()=>{const s=fixture();s.draft=startWorkout(s,s.routines[0]);assert.deepEqual(validateBackup(JSON.parse(JSON.stringify(s))),s)});
test('orphan completed drop remains loadable after finish',()=>{const s=initialState(),w=startWorkout(s);w.entries=[{id:'entry',exerciseId:'bench-press',group:null,sets:[newSet(100,5),{...newSet(60,10,'drop'),done:true}]}];s.workouts=[finishWorkout(w)];assert.equal(s.workouts[0].entries[0].sets[0].type,'normal');assert.doesNotThrow(()=>validateBackup(s))});
test('warmup excluded and drop included in volume; drop excluded in PR',()=>{const s=fixture(),w=s.workouts[0];w.entries[0].sets.unshift({...newSet(200,3,'warmup'),done:true});assert.equal(volume(w),1100);assert.equal(bestFor(s.workouts,'bench-press').weight,100);assert.ok(Math.abs(bestFor(s.workouts,'bench-press').e1rm-116.6666666667)<1e-6)});
test('unit display conversion never changes canonical kg',()=>{const s=fixture(),before=JSON.stringify(s.workouts);s.settings.unit='lb';assert.equal(toDisplay(100,'lb'),220.46);s.settings.unit='kg';assert.equal(JSON.stringify(s.workouts),before);assert.ok(Math.abs(toKg(220.462262185,'lb')-100)<1e-10)});
test('empty, negative and invalid imported records reject',()=>{assert.throws(()=>finishWorkout(startWorkout(initialState())));for(const value of [-1,null,Infinity]){const s=fixture();s.workouts[0].entries[0].sets[0].weight=value;assert.throws(()=>validateBackup(s))}});
test('bad IDs and duplicate references cannot enter storage',()=>{const s=fixture();s.exercises[0].id='x" onclick="evil';assert.throws(()=>validateBackup(s));const t=fixture();t.workouts.push(structuredClone(t.workouts[0]));assert.throws(()=>validateBackup(t))});
test('bodyweight 0 is valid with reps',()=>{const s=fixture();s.workouts[0].entries[0].sets=[{...newSet(0,10),done:true}];assert.doesNotThrow(()=>validateBackup(s));assert.equal(volume(s.workouts[0]),0)});
test('removing a superset member leaves no orphan group',()=>{const entries=[{group:'g'},{group:'g'}];normalizeGroups(entries);assert.equal(entries[0].group,'g');entries.pop();normalizeGroups(entries);assert.equal(entries[0].group,null)});
test('duration buckets add multiple same-day workouts',()=>{const s=fixture(),w=s.workouts[0];w.started='2026-09-21T10:00:00';w.ended='2026-09-21T10:20:00';const copy=structuredClone(w);copy.id='second';copy.started='2026-09-21T12:00:00';copy.ended='2026-09-21T13:20:00';s.workouts.push(copy);const d=activityDays(s,112,new Date('2026-09-24T12:00:00')).find(d=>d.date==='2026-09-21');assert.equal(d.count,2);assert.equal(d.minutes,100);assert.equal(d.level,4)});
test('missed days respect historical schedules and never mark today missed',()=>{const s=initialState();s.settings.trackingSince='2026-09-01';s.settings.schedule=[4];s.settings.scheduleHistory=[{from:'2026-09-01',days:[1]},{from:'2026-09-23',days:[4]}];const days=activityDays(s,112,new Date('2026-09-24T12:00:00'));assert.equal(days.find(d=>d.date==='2026-09-21').status,'missed');assert.equal(days.find(d=>d.date==='2026-09-24').status,'planned');assert.equal(days.find(d=>d.date==='2026-09-25').status,'future')});
test('CSV escapes formulas and quoted names',()=>{const s=fixture();s.workouts[0].name='=SUM(1,2)';s.workouts[0].notes='He said "good"';const csv=csvExport(s);assert.ok(csv.includes("\"'=SUM(1,2)\""));assert.ok(csv.includes('He said ""good""'))});
test('deleting workouts recalculates records without stale state',()=>{const s=fixture();assert.equal(bestFor(s.workouts,'bench-press').weight,100);s.workouts=[];assert.equal(bestFor(s.workouts,'bench-press').weight,null)});
